### PR TITLE
Add/GitHub actions

### PR DESCRIPTION
**Pull request by theavege**
I add github-actions

### CODE REVIEW

**Comment by theavege** [comment]
Made changes based on [recommendations](https://github.com/gcarreno/blink-my-duino/pull/2#issuecomment-2463857014).

**Comment by theavege** [comment]
@wp-xyz Could you, please, merge this PR?

**Comment by wp-xyz** [comment]
Why were you adding the res file? Isn't it created automatically upon compilation?

**Comment by theavege** [comment]
The res file created automatically upon compilation.

**Comment by wp-xyz** [comment]
Just wondering: Then github actions must be adding the res file to the project. Because I had not included in .gitignore?

**Pull request merged**
